import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'brand-green': '#00ed64',
        'brand-green-dark': '#00684a',
        'brand-green-mid': '#00a35c',
        'brand-green-soft': '#c3f0d2',
        'brand-teal-deep': '#001e2b',
        'brand-teal': '#003d4f',
        'brand-teal-mid': '#00684a',
        'accent-purple': '#7b3ff2',
        'accent-orange': '#fa6e39',
        'accent-pink': '#f06bb8',
        'accent-blue': '#3d4f9f',
        'semantic-warning-bg': '#fff8e0',
        'semantic-warning-text': '#946f3f',
        'canvas': '#ffffff',
        'canvas-dark': '#001e2b',
        'surface': '#f9fbfa',
        'surface-soft': '#f4f7f6',
        'surface-feature': '#e3fcef',
        'hairline': '#e1e5e8',
        'hairline-soft': '#eceff1',
        'hairline-strong': '#c1ccd6',
        'hairline-dark': '#1c2d38',
        'ink': '#001e2b',
        'charcoal': '#1c2d38',
        'slate': '#3d4f5b',
        'steel': '#5c6c7a',
        'stone': '#7c8c9a',
        'muted': '#a8b3bc',
        'on-dark': '#ffffff',
        'on-dark-muted': '#a8b3bc',
      },
      fontFamily: {
        'euclid': ['system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        'source-code': ['SF Mono', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      borderRadius: {
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        'xxl': '24px',
        'full': '9999px',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '20px',
        'xl': '24px',
        'xxl': '32px',
        'xxxl': '40px',
        'section-sm': '48px',
        'section': '64px',
        'section-lg': '96px',
        'hero': '120px',
      },
      boxShadow: {
        'card': '0 4px 12px 0 rgba(0, 30, 43, 0.08)',
        'mockup': '0 12px 24px -4px rgba(0, 30, 43, 0.12)',
        'modal': '0 16px 48px -8px rgba(0, 30, 43, 0.16)',
      },
      fontSize: {
        'hero-display': ['72px', { lineHeight: '1.10', letterSpacing: '-1.5px', fontWeight: '500' }],
        'display-lg': ['56px', { lineHeight: '1.15', letterSpacing: '-1px', fontWeight: '500' }],
        'heading-1': ['48px', { lineHeight: '1.20', letterSpacing: '-0.5px', fontWeight: '500' }],
        'heading-2': ['36px', { lineHeight: '1.25', letterSpacing: '-0.5px', fontWeight: '500' }],
        'heading-3': ['28px', { lineHeight: '1.30', fontWeight: '500' }],
        'heading-4': ['22px', { lineHeight: '1.35', fontWeight: '500' }],
        'heading-5': ['18px', { lineHeight: '1.40', fontWeight: '600' }],
        'subtitle': ['18px', { lineHeight: '1.50', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-md-medium': ['16px', { lineHeight: '1.55', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.50', fontWeight: '400' }],
        'body-sm-medium': ['14px', { lineHeight: '1.50', fontWeight: '500' }],
        'caption': ['13px', { lineHeight: '1.40', fontWeight: '400' }],
        'caption-bold': ['13px', { lineHeight: '1.40', fontWeight: '600' }],
        'micro': ['12px', { lineHeight: '1.40', fontWeight: '500' }],
        'micro-uppercase': ['11px', { lineHeight: '1.40', fontWeight: '600', letterSpacing: '1px' }],
        'button-md': ['14px', { lineHeight: '1.30', fontWeight: '600' }],
        'code-md': ['14px', { lineHeight: '1.55', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

export default config
