"""
Tests for generated docx format verification.

Validates that documents generated by the generator match the feature profile
extracted from finalized patents. This closes the loop:

  定稿文件 → extract features → profile → generator → output docx
                                                         ↓
                                              verify output matches profile
"""

import statistics
from pathlib import Path

import pytest
from docx import Document
from docx.oxml.ns import qn

from src.document_gen.feature_extractor import extract_profile
from src.document_gen.feature_profile import PatentFeatureProfile
from src.document_gen.generator import generate_patent_docx, set_profile, reset_profile
from src.models.domain import Claim, DescriptionSection, PatentDraft

# Path to finalized patents
FINALIZED_DIR = Path(__file__).resolve().parent.parent.parent / "定稿文件"

pytestmark = pytest.mark.skipif(
    not FINALIZED_DIR.exists(),
    reason="定稿文件 directory not found",
)


@pytest.fixture(scope="module")
def profile() -> PatentFeatureProfile:
    """Extract profile from reference files."""
    return extract_profile(FINALIZED_DIR)


@pytest.fixture(scope="module")
def sample_draft() -> PatentDraft:
    """Create a sample patent draft for generation tests."""
    return PatentDraft(
        title="一种基于多模态融合的智能诊断方法及系统",
        technical_field="本发明涉及人工智能技术领域，具体涉及一种基于多模态融合的智能诊断方法及系统。",
        background_art=DescriptionSection(
            section_name="背景技术",
            content="随着医疗数据的快速增长，传统的单模态诊断方法已无法满足临床需求。\n现有技术中，大多数诊断系统仅依赖单一数据源，导致诊断准确率受限。",
            word_count=60,
        ),
        summary_of_invention=DescriptionSection(
            section_name="发明内容",
            content="为解决上述技术问题，本发明提供一种基于多模态融合的智能诊断方法。\n本发明通过融合影像、文本和结构化数据，显著提高了诊断准确率。",
            word_count=50,
        ),
        detailed_description=DescriptionSection(
            section_name="具体实施方式",
            content="为使本发明实施例的目的、技术方案和优点更加清楚，下面将结合附图进行描述。\n需要说明的是，本实施例中的多模态融合模块包括特征对齐层和注意力融合层。\n需要说明的是，特征对齐层通过投影矩阵将不同模态的特征映射到统一的语义空间。",
            word_count=100,
        ),
        claims=[
            Claim(
                claim_number=1,
                claim_type="independent",
                content="基于多模态融合的智能诊断方法，其特征在于，包括：获取多模态医疗数据；通过特征对齐层将多模态数据映射到统一语义空间；基于注意力融合层进行跨模态特征融合；输出诊断结果。",
                category="method",
            ),
            Claim(
                claim_number=2,
                claim_type="dependent",
                content="所述多模态医疗数据包括医学影像数据、电子病历文本数据和实验室检测数据。",
                dependencies=[1],
                category="method",
            ),
            Claim(
                claim_number=3,
                claim_type="dependent",
                content="所述注意力融合层采用多头交叉注意力机制。",
                dependencies=[1],
                category="method",
            ),
        ],
        abstract="本发明提供一种基于多模态融合的智能诊断方法及系统，通过特征对齐和注意力融合机制，整合影像、文本和结构化医疗数据，提高了诊断准确率。",
    )


@pytest.fixture(scope="module")
def generated_doc(profile, sample_draft, tmp_path_factory) -> Document:
    """Generate a docx and return the parsed Document for verification."""
    # Set the profile for the generator
    set_profile(profile)

    tmp = tmp_path_factory.mktemp("gen")
    filepath = generate_patent_docx(sample_draft, "test-format-001", tmp)

    doc = Document(filepath)
    reset_profile()
    return doc


# ═══════════════════════════════════════════════════════════════════════════════
# Test: Page Layout Matches Profile
# ═══════════════════════════════════════════════════════════════════════════════


class TestPageLayout:
    """Verify generated document page layout matches profile."""

    def test_page_size(self, generated_doc, profile):
        """Page size matches profile (A4)."""
        section = generated_doc.sections[0]
        assert section.page_width.cm == pytest.approx(profile.page_layout.page_width_cm, abs=0.1)
        assert section.page_height.cm == pytest.approx(profile.page_layout.page_height_cm, abs=0.1)

    def test_five_sections(self, generated_doc, profile):
        """Document has correct number of sections."""
        assert len(generated_doc.sections) == profile.document_structure.num_sections

    def test_abstract_margins(self, generated_doc, profile):
        """摘要 section margins match profile."""
        s = generated_doc.sections[0]
        expected = profile.page_layout.margins_abstract
        assert s.top_margin.cm == pytest.approx(expected[0], abs=0.05)
        assert s.bottom_margin.cm == pytest.approx(expected[1], abs=0.05)
        assert s.left_margin.cm == pytest.approx(expected[2], abs=0.05)
        assert s.right_margin.cm == pytest.approx(expected[3], abs=0.05)

    def test_claims_margins(self, generated_doc, profile):
        """权利要求书 section margins match profile."""
        s = generated_doc.sections[2]  # 3rd section = claims
        expected = profile.page_layout.margins_claims
        assert s.top_margin.cm == pytest.approx(expected[0], abs=0.05)
        assert s.bottom_margin.cm == pytest.approx(expected[1], abs=0.05)
        assert s.left_margin.cm == pytest.approx(expected[2], abs=0.05)
        assert s.right_margin.cm == pytest.approx(expected[3], abs=0.05)

    def test_description_margins(self, generated_doc, profile):
        """说明书 section margins match profile."""
        s = generated_doc.sections[3]  # 4th section = description
        expected = profile.page_layout.margins_description
        assert s.top_margin.cm == pytest.approx(expected[0], abs=0.05)
        assert s.bottom_margin.cm == pytest.approx(expected[1], abs=0.05)
        assert s.left_margin.cm == pytest.approx(expected[2], abs=0.05)
        assert s.right_margin.cm == pytest.approx(expected[3], abs=0.05)


# ═══════════════════════════════════════════════════════════════════════════════
# Test: Typography Matches Profile
# ═══════════════════════════════════════════════════════════════════════════════


class TestTypography:
    """Verify generated fonts/sizes match profile."""

    def test_body_font_name(self, generated_doc, profile):
        """Body text font matches profile."""
        for para in generated_doc.paragraphs:
            style = para.style.name if para.style else ""
            if "Heading" in style or not para.text.strip() or not para.runs:
                continue
            run = para.runs[0]
            assert run.font.name == profile.typography.body_font_name
            break

    def test_body_font_size(self, generated_doc, profile):
        """Body text size matches profile."""
        for para in generated_doc.paragraphs:
            style = para.style.name if para.style else ""
            if "Heading" in style or not para.text.strip() or not para.runs:
                continue
            run = para.runs[0]
            assert run.font.size.pt == pytest.approx(
                profile.typography.body_font_size_pt, abs=0.5
            )
            break

    def test_body_font_east_asian(self, generated_doc, profile):
        """East-Asian font attribute set correctly."""
        for para in generated_doc.paragraphs:
            style = para.style.name if para.style else ""
            if "Heading" in style or not para.text.strip() or not para.runs:
                continue
            run = para.runs[0]
            rPr = run._element.find(qn("w:rPr"))
            rFonts = rPr.find(qn("w:rFonts")) if rPr is not None else None
            if rFonts is not None:
                ea = rFonts.get(qn("w:eastAsia"))
                assert ea == profile.typography.body_font_name
            break

    def test_heading_font(self, generated_doc, profile):
        """Document heading font matches profile."""
        for para in generated_doc.paragraphs:
            style = para.style.name if para.style else ""
            if "Heading" in style and para.text.strip() and para.runs:
                run = para.runs[0]
                assert run.font.name == profile.typography.doc_heading_font_name
                break


# ═══════════════════════════════════════════════════════════════════════════════
# Test: Paragraph Format Matches Profile
# ═══════════════════════════════════════════════════════════════════════════════


class TestParagraphFormat:
    """Verify paragraph formatting matches profile."""

    def test_first_line_indent(self, generated_doc, profile):
        """Body text first line indent matches profile."""
        for para in generated_doc.paragraphs:
            style = para.style.name if para.style else ""
            if "Heading" in style or not para.text.strip():
                continue
            fmt = para.paragraph_format
            if fmt.first_line_indent:
                actual = fmt.first_line_indent.cm
                expected = profile.paragraph_format.body_first_line_indent_cm
                assert actual == pytest.approx(expected, abs=0.05)
                break

    def test_line_spacing(self, generated_doc, profile):
        """Body text line spacing matches profile (in twips via XML)."""
        expected_twips = round(profile.paragraph_format.body_line_spacing_emu / 635)

        for para in generated_doc.paragraphs:
            style = para.style.name if para.style else ""
            if "Heading" in style or not para.text.strip():
                continue
            pPr = para._element.find(qn("w:pPr"))
            if pPr is not None:
                spacing = pPr.find(qn("w:spacing"))
                if spacing is not None:
                    line_val = spacing.get(qn("w:line"))
                    line_rule = spacing.get(qn("w:lineRule"))
                    if line_val and line_rule == "exact":
                        assert int(line_val) == expected_twips
                        return

        pytest.fail("No paragraph with exact line spacing found")

    def test_body_alignment_justify(self, generated_doc, profile):
        """Body text alignment matches profile."""
        for para in generated_doc.paragraphs:
            style = para.style.name if para.style else ""
            if "Heading" in style or not para.text.strip():
                continue
            if para.paragraph_format.first_line_indent:
                # This is a body paragraph
                assert para.paragraph_format.alignment == pytest.approx(3)  # JUSTIFY = 3
                break

    def test_heading_alignment_center(self, generated_doc, profile):
        """Document headings are centered."""
        for para in generated_doc.paragraphs:
            style = para.style.name if para.style else ""
            if "Heading" in style and para.text.strip():
                assert para.alignment == pytest.approx(1)  # CENTER = 1
                break


# ═══════════════════════════════════════════════════════════════════════════════
# Test: Document Structure Matches Profile
# ═══════════════════════════════════════════════════════════════════════════════


class TestDocumentStructure:
    """Verify document structure matches profile."""

    def test_section_count(self, generated_doc, profile):
        """Correct number of document sections."""
        assert len(generated_doc.sections) == profile.document_structure.num_sections

    def test_heading_char_spacing(self, generated_doc, profile):
        """Document headings have spaced characters."""
        sep = profile.document_structure.heading_char_separator
        for para in generated_doc.paragraphs:
            style = para.style.name if para.style else ""
            if "Heading" in style and para.text.strip():
                # Verify characters are separated
                assert sep in para.text
                break

    def test_description_subsections_present(self, generated_doc, profile):
        """All expected description sub-sections are present."""
        expected = set(profile.document_structure.description_sections)
        found = set()

        for para in generated_doc.paragraphs:
            text = para.text.strip()
            if text in expected and para.runs and para.runs[0].bold:
                found.add(text)

        # At minimum: 技术领域, 背景技术, 发明内容, 具体实施方式
        required = {"技术领域", "背景技术", "发明内容", "具体实施方式"}
        assert required.issubset(found), f"Missing: {required - found}"


# ═══════════════════════════════════════════════════════════════════════════════
# Test: Content Patterns Match Profile
# ═══════════════════════════════════════════════════════════════════════════════


class TestContentPatterns:
    """Verify content formatting patterns match profile."""

    def test_claim_numbering(self, generated_doc, profile):
        """Claims use correct numbering separator."""
        sep = profile.content_patterns.claim_numbering_separator
        for para in generated_doc.paragraphs:
            text = para.text.strip()
            if text.startswith("1" + sep):
                assert True
                return
        pytest.fail("No claim with correct numbering found")

    def test_dependent_claim_format(self, generated_doc, profile):
        """Dependent claims use format from profile."""
        dep_marker = "根据权利要求"
        for para in generated_doc.paragraphs:
            text = para.text.strip()
            if dep_marker in text:
                assert True
                return
        pytest.fail("No dependent claim found")
