"""Workflow loop thresholds and timeout constants."""

from __future__ import annotations

QUALITY_REMEDIATION_THRESHOLD = 0.9
QUALITY_REMEDIATION_SAFETY_LIMIT = 12

WRITER_INITIAL_TIMEOUT_SECONDS = 1800
WRITER_REVISION_TIMEOUT_SECONDS = 1200
WRITER_DRAWING_REPAIR_TIMEOUT_SECONDS = 1200

AGENT_CONVERSATION_TIMEOUT_SECONDS = 600

