# -*- coding: utf-8 -*-
"""WorkflowQualityGateMixin methods split from the workflow engine."""
from .shared import *


class WorkflowQualityGateMixin:
    def _validate_drawing_files_for_review(self, draft: Dict[str, Any]) -> Dict[str, Any]:
        """Return deterministic drawing-file facts for the reviewer.

        This is not a quality judgment. It only reports local file facts so the
        quality Agent does not need browser remote-debug access to inspect files
        generated by the writer tool.
        """
        drawings = draft.get("drawings", []) if isinstance(draft, dict) else []
        if not isinstance(drawings, list):
            drawings = []
        items: List[Dict[str, Any]] = []
        digests: Dict[str, str] = {}
        issues: List[Dict[str, str]] = []

        for drawing in drawings:
            if not isinstance(drawing, dict):
                continue
            figure_number = str(drawing.get("figure_number") or drawing.get("figureNumber") or "")
            file_path = str(drawing.get("file_path") or drawing.get("path") or "")
            item: Dict[str, Any] = {
                "figure_number": figure_number,
                "file_path": file_path,
                "exists": False,
                "is_file": False,
                "size_bytes": 0,
                "sha256": "",
            }
            if not file_path:
                issues.append({
                    "figure_number": figure_number,
                    "issue": "附图缺少本地文件路径",
                })
                items.append(item)
                continue
            try:
                path = _Path(file_path)
                item["exists"] = path.exists()
                item["is_file"] = path.is_file()
                if path.is_file():
                    data = path.read_bytes()
                    item["size_bytes"] = len(data)
                    import hashlib

                    digest = hashlib.sha256(data).hexdigest()
                    item["sha256"] = digest
                    if not data:
                        issues.append({
                            "figure_number": figure_number,
                            "issue": "附图文件为空",
                        })
                    if digest in digests:
                        issues.append({
                            "figure_number": figure_number,
                            "issue": f"附图文件内容与{digests[digest]}完全相同",
                        })
                    else:
                        digests[digest] = figure_number
                else:
                    issues.append({
                        "figure_number": figure_number,
                        "issue": "附图文件路径不存在或不是文件",
                    })
            except Exception as exc:
                issues.append({
                    "figure_number": figure_number,
                    "issue": f"附图文件校验异常：{str(exc)[:120]}",
                })
            items.append(item)

        return {
            "checked_by": "workflow_local_file_validator",
            "drawing_count": len(items),
            "all_files_accessible": bool(items) and not issues,
            "all_files_non_empty": all(int(item.get("size_bytes") or 0) > 0 for item in items) if items else False,
            "all_file_hashes_distinct": len({item.get("sha256") for item in items if item.get("sha256")}) == len(items) if items else False,
            "items": items,
            "issues": issues,
        }

    def _review_has_false_drawing_access_system_failure(
        self,
        context: WorkflowContext,
        review_report: Dict[str, Any],
    ) -> bool:
        if not isinstance(review_report, dict) or not isinstance(context.patent_draft, dict):
            return False
        validation = self._validate_drawing_files_for_review(context.patent_draft)
        if not validation.get("all_files_accessible"):
            return False
        text = "\n".join(self._iter_phase_text_values(review_report))
        drawing_markers = ("附图", "图片", "图1", "图2", "图3", "图4", "图5", "drawing", "figure")
        browser_markers = ("浏览器", "远程调试", "remote", "debug", "web_access", "CDP")
        return any(marker in text for marker in drawing_markers) and any(
            marker in text for marker in browser_markers
        )

    def _downgrade_false_drawing_access_system_failures(
        self,
        context: WorkflowContext,
        review_report: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Do not let browser-debug availability override real local file facts."""
        if not self._review_has_false_drawing_access_system_failure(context, review_report):
            return review_report
        merged = dict(review_report)
        for section_key in (
            "formal_compliance_review",
            "claims_review",
            "description_review",
            "consistency_review",
            "drawing_review",
            "drawings_review",
            "figure_review",
        ):
            section = merged.get(section_key)
            if not isinstance(section, dict) or not isinstance(section.get("issues"), list):
                continue
            updated_issues = []
            for issue in section.get("issues") or []:
                if not isinstance(issue, dict):
                    updated_issues.append(issue)
                    continue
                issue_text = "\n".join(self._iter_phase_text_values(issue))
                is_false_access_issue = (
                    str(issue.get("responsible_phase") or "").strip().lower() == "system_failure"
                    and any(marker in issue_text for marker in ("浏览器", "远程调试", "web_access", "remote", "debug", "CDP"))
                    and any(marker in issue_text for marker in ("附图", "图片", "图1", "图2", "图3", "图4", "图5", "drawing", "figure"))
                )
                if is_false_access_issue:
                    patched = dict(issue)
                    patched["severity"] = "low"
                    patched["responsible_phase"] = "patent_writing"
                    patched["description"] = (
                        str(patched.get("description") or "")
                        + "；工作流已通过本地文件校验确认附图文件存在、非空且文件内容不重复，"
                        "浏览器远程调试未连接不作为阻断项。"
                    )
                    patched["source"] = "downgraded_by_workflow_local_file_validator"
                    updated_issues.append(patched)
                else:
                    updated_issues.append(issue)
            section = dict(section)
            section["issues"] = updated_issues
            merged[section_key] = section
        if str(merged.get("root_cause") or "").strip().lower() == "system_failure":
            merged["root_cause"] = "content_incomplete"
        merged["drawing_file_validation"] = self._validate_drawing_files_for_review(
            context.patent_draft
        )
        return merged

    def _check_review_needs_revision(self, review_report: Dict[str, Any]) -> bool:
        """检查质量审查报告是否有需要修正的严重/高级别问题

        关键：必须最先检查 _agent_failed 标记 — 当审查 Agent 自身执行失败
        时 (LLM API 错误、超时等),即使结构化字段都为空,也必须返回 True
        触发 iteration loop 重新审查。否则会出现"流程结束但实际未审查"的情况。
        """
        if not isinstance(review_report, dict):
            return True  # 审查报告不是 dict 视为异常,触发重试

        # Agent 自身执行失败 (同时检查 normalized 标记 _agent_failed 和原始字段 failed)
        if review_report.get("_agent_failed") is True:
            return True
        if review_report.get("failed") is True:
            return True

        # 检查recommendation字段
        recommendation = review_report.get("recommendation", "")
        if recommendation in ("reject", "revise"):
            return True

        # 检查review_summary
        summary = review_report.get("review_summary", {})
        if isinstance(summary, dict):
            if summary.get("recommendation") in ("reject", "revise"):
                return True
            rating = summary.get("overall_rating", "")
            if rating in ("needs_revision", "poor"):
                return True

        # 检查revision_priority
        priority = review_report.get("revision_priority", "")
        if priority in ("critical", "high"):
            return True

        # 检查各子审查中是否有严重问题
        for section_key in (
            "formal_compliance_review",
            "claims_review",
            "description_review",
            "consistency_review",
            "drawing_review",
            "drawings_review",
            "figure_review",
        ):
            section = review_report.get(section_key, {})
            if isinstance(section, dict):
                issues = section.get("issues", [])
                for issue in issues:
                    if isinstance(issue, dict) and issue.get("severity") in ("critical", "high"):
                        return True

        # 检查examination_risks中的高风险
        for risk in review_report.get("examination_risks", []):
            if isinstance(risk, dict) and risk.get("likelihood") in ("critical", "high"):
                return True

        return False

    def _extract_normalized_review_score(self, review_report: Dict[str, Any]) -> Optional[float]:
        """提取并归一化审查分数到 0-1 区间。"""
        if not isinstance(review_report, dict):
            return None

        score_candidates = [
            review_report.get("overall_score"),
            (review_report.get("review_summary") or {}).get("overall_score")
            if isinstance(review_report.get("review_summary"), dict)
            else None,
            review_report.get("score"),
        ]

        for raw_score in score_candidates:
            if isinstance(raw_score, (int, float)):
                score = float(raw_score)
                if 0 <= score <= 1:
                    return score
                if 1 < score <= 100:
                    return score / 100
        return None

    def _needs_quality_remediation(self, review_report: Dict[str, Any]) -> bool:
        """统一判断质量问题是否还需要补救。"""
        if not isinstance(review_report, dict) or not review_report:
            return True
        recommendation = str(
            review_report.get("recommendation")
            or (
                review_report.get("review_summary", {}).get("recommendation")
                if isinstance(review_report.get("review_summary"), dict)
                else ""
            )
            or ""
        ).strip().lower()
        if recommendation not in {"approve", "pass", "accept", "revise", "reject"}:
            return True
        if self._check_review_needs_revision(review_report):
            return True
        normalized_score = self._extract_normalized_review_score(review_report)
        if normalized_score is None:
            return True
        return normalized_score < QUALITY_REMEDIATION_THRESHOLD

    def _classify_remediation_path(self, review_report: Dict[str, Any], context: WorkflowContext) -> str:
        """按根因把补救动作分流为写/分析/检索/等用户/终止。"""
        if self._iteration_making_no_progress(context):
            return "TERMINAL_FAILURE"

        if not isinstance(review_report, dict):
            return "TERMINAL_FAILURE"

        root_cause = str(review_report.get("root_cause") or "").strip().lower()
        root_mapping = {
            "content_incomplete": "WRITE_MORE",
            "requirement_unclear": "ANALYZE_MORE",
            "evidence_missing": "SEARCH_MORE",
            "external_info_missing": self._route_missing_information(review_report),
            "system_failure": "TERMINAL_FAILURE",
        }
        root_route = root_mapping.get(root_cause)

        route_mapping = {
            "patent_writing": "WRITE_MORE",
            "writing": "WRITE_MORE",
            "requirement_analysis": "ANALYZE_MORE",
            "requirements": "ANALYZE_MORE",
            "retrieval_analysis": "SEARCH_MORE",
            "retrieval": "SEARCH_MORE",
            "user_input": "NEEDS_USER_INPUT",
            "system_failure": "TERMINAL_FAILURE",
        }
        routed_phases: set[str] = set()
        for issue in self._extract_review_issue_records(review_report):
            responsible_phase = str(
                issue.get("responsible_phase")
                or issue.get("target_phase")
                or issue.get("route_to")
                or ""
            ).strip().lower()
            if responsible_phase in route_mapping:
                routed_phases.add(responsible_phase)

        # A review can contain both drafting defects and evidence defects. Evidence
        # defects must be resolved before the writer is asked to revise again,
        # otherwise the writer keeps rewriting from the same incomplete source set.
        #
        # A low/medium "system_failure" note is often a non-blocking process
        # reminder such as "final DOCX has not been generated yet" during the
        # pre-DOCX quality gate. That must not terminate the agent loop.
        has_blocking_system_failure = any(
            str(issue.get("responsible_phase") or issue.get("target_phase") or issue.get("route_to") or "")
            .strip()
            .lower()
            == "system_failure"
            and str(issue.get("severity") or issue.get("likelihood") or "").strip().lower()
            in {"high", "critical"}
            for issue in self._extract_review_issue_records(review_report)
            if isinstance(issue, dict)
        )
        if has_blocking_system_failure:
            return "TERMINAL_FAILURE"

        # The reviewer-level root cause is the primary routing signal. Individual
        # risk records can name retrieval_analysis for later evidence hardening,
        # but if the reviewer's top-level cause is content_incomplete the next
        # action must be a writer revision based on the already confirmed facts.
        if root_route and root_route != "TERMINAL_FAILURE":
            return root_route

        if "retrieval_analysis" in routed_phases or "retrieval" in routed_phases:
            return "SEARCH_MORE"
        if "requirement_analysis" in routed_phases or "requirements" in routed_phases:
            return "ANALYZE_MORE"
        if "patent_writing" in routed_phases or "writing" in routed_phases:
            return "WRITE_MORE"
        if "user_input" in routed_phases:
            return "NEEDS_USER_INPUT"

        if root_route:
            return root_route

        missing_information = review_report.get("missing_information", [])
        if isinstance(missing_information, list) and any(str(item).strip() for item in missing_information):
            return self._route_missing_information(review_report)

        draft_issues = self._validate_patent_draft_completeness(context.patent_draft)
        if any(
            issue in draft_issues
            for issue in (
                "claims_missing",
                "independent_claim_missing",
                "dependent_claims_missing",
                "description_missing",
                "description_technical_field_missing",
                "description_background_art_missing",
                "description_summary_of_invention_missing",
                "description_detailed_description_missing",
                "abstract_missing",
                "drawing_artifacts_missing",
            )
        ):
            return "WRITE_MORE"

        if self._needs_quality_remediation(review_report):
            return "WRITE_MORE"
        return "TERMINAL_FAILURE"

    def _route_missing_information(self, review_report: Dict[str, Any]) -> str:
        """Route missing information back to the Agent most likely to resolve it first.

        Missing information is not automatically a user-blocking state. Most
        quality findings should go back through requirement analysis or
        retrieval so Agents can refine the shared facts, change search
        strategies, and only ask the user after the remediation loop is unable
        to make progress.
        """
        if not isinstance(review_report, dict):
            return "ANALYZE_MORE"

        missing_information = review_report.get("missing_information", [])
        if not isinstance(missing_information, list):
            missing_information = [missing_information]
        text = "\n".join(str(item) for item in missing_information if str(item).strip()).lower()

        search_markers = (
            "检索",
            "证据",
            "公开",
            "网页",
            "专利",
            "prior art",
            "patent",
            "google patents",
            "uspto",
            "对比文件",
            "真伪",
            "核验",
            "来源",
        )
        if any(marker.lower() in text for marker in search_markers):
            return "SEARCH_MORE"

        return "ANALYZE_MORE"

    def _resolve_remediation_resume_phase(self, classification: str) -> WorkflowState:
        mapping = {
            "WRITE_MORE": WorkflowState.PATENT_WRITING,
            "ANALYZE_MORE": WorkflowState.REQUIREMENT_ANALYSIS,
            "SEARCH_MORE": WorkflowState.RETRIEVAL_ANALYSIS,
            "NEEDS_USER_INPUT": WorkflowState.REQUIREMENT_ANALYSIS,
            "AUTO_REMEDIATION_LIMIT": WorkflowState.PATENT_WRITING,
        }
        return mapping.get(classification, WorkflowState.PATENT_WRITING)

    def _enter_quality_remediation_hold(
        self,
        context: WorkflowContext,
        review_report: Dict[str, Any],
        classification: str,
    ) -> None:
        normalized_score = self._extract_normalized_review_score(review_report)
        missing_information = review_report.get("missing_information", [])
        if not isinstance(missing_information, list):
            missing_information = []

        context.metadata["quality_remediation"] = {
            "current_score": normalized_score,
            "threshold": QUALITY_REMEDIATION_THRESHOLD,
            "classification": classification.lower(),
            "missing_information": [str(item).strip() for item in missing_information if str(item).strip()],
            "attempt_count": context.iteration_count,
            "recommended_next_action": (
                "provide_info"
                if classification in {"AUTO_REMEDIATION_LIMIT", "NEEDS_USER_INPUT"}
                else "continue_auto_fix"
            ),
            "resume_phase": self._resolve_remediation_resume_phase(classification).value,
        }

    def _prewriting_requires_user_input(self, blockers: List[Dict[str, str]]) -> bool:
        """True when the writer gate found invention facts the Agents may need from user.

        This is a classification signal, not an immediate stop condition. The CEO
        still gets remediation rounds first so the responsible Agent can reuse the
        prior result, apply feedback, search again, or infer what is reasonably
        inferable. Only after the retry budget is exhausted should the workflow
        pause for user discussion.
        """
        user_fact_markers = (
            "必须由用户",
            "需要用户提供",
            "请用户提供",
            "用户提供",
            "用户补充",
            "用户确认",
            "产品名",
            "展厅名",
            "供应商",
            "公开链接",
            "genuinely_missing",
            "external_info_missing",
        )
        agent_resolvable_markers = (
            "检索",
            "现有技术",
            "对比文件",
            "证据",
            "可核验",
            "Google Patents",
            "USPTO",
            "专业/官方",
            "交叉核验",
            "技术问题",
            "技术方案",
            "保护主题",
            "创新点",
            "权利要求骨架",
            "实施方式",
            "映射关系",
            "补偿",
            "裁切",
            "算法",
        )
        for blocker in blockers:
            if blocker.get("phase") == WorkflowState.RETRIEVAL_ANALYSIS.value:
                continue
            message = str(blocker.get("message") or "")
            if any(marker in message for marker in agent_resolvable_markers):
                continue
            if any(marker in message for marker in user_fact_markers):
                return True
        return False

    def _iter_phase_text_values(self, value: Any) -> List[str]:
        texts: List[str] = []
        if isinstance(value, str):
            if value.strip():
                texts.append(value)
        elif isinstance(value, dict):
            for nested in value.values():
                texts.extend(self._iter_phase_text_values(nested))
        elif isinstance(value, list):
            for item in value:
                texts.extend(self._iter_phase_text_values(item))
        return texts

    def _has_phase_signal(self, value: Any, *needles: str) -> bool:
        combined = "\n".join(self._iter_phase_text_values(value)).lower()
        return any(needle.lower() in combined for needle in needles)

    def _as_nonempty_list(self, value: Any) -> List[Any]:
        if isinstance(value, list):
            return [item for item in value if str(item).strip()]
        if isinstance(value, str) and value.strip():
            return [value.strip()]
        return []

    def _is_nonblocking_prewriting_gap(
        self, gap_text: Any, retrieval_report: Optional[Dict[str, Any]] = None
    ) -> bool:
        """Return True for limitations that should be carried as risk, not block writing.

        A single unavailable retrieval source is not a hard failure when other
        verifiable sources exist. Likewise, implementation values that can be
        expressed as ranges or alternatives should be handled by the writer and
        reviewer instead of trapping the workflow before DOCX generation.
        """
        if isinstance(gap_text, (dict, list)):
            text = "\n".join(self._iter_phase_text_values(gap_text))
        else:
            text = str(gap_text or "")
        if not text.strip():
            return True
        has_evidence = (
            isinstance(retrieval_report, dict)
            and self._has_real_retrieval_evidence(retrieval_report)
        )
        has_negative_retrieval_audit = (
            isinstance(retrieval_report, dict)
            and self._has_auditable_negative_retrieval(retrieval_report)
        )
        unavailable_source_markers = (
            "未配置",
            "未启用",
            "不可用",
            "无法访问",
            "HTTP 503",
            "解析失败",
            "未取得直接检索结果",
            "数据库覆盖",
            "覆盖不足",
            "未完成系统性直接检索",
            "尚未完成系统性直接检索",
            "未完成系统性检索",
            "系统性直接检索",
            "系统性结果",
            "稳定可核验结果",
            "直接检索",
            "宽检索",
            "英文专利宽检索",
            "继续英文专利检索",
            "商业专利库",
            "数据源",
            "不应要求用户补充",
            "最接近对比文件",
            "最接近专利文件",
            "直接披露",
            "直接公开",
            "中国专利数据库",
            "中文专利源",
            "CNIPA",
            "可核验中文",
            "未获得直接",
            "未取得任何可写入",
            "similar_patents",
            "可核验专利文献",
            "可写入",
            "公开号",
            "申请人",
            "公开日",
            "核心公开内容",
            "中文专利证据",
            "专利证据",
            "专利文献",
            "最接近专利文献",
            "行业痛点",
            "背景公开证据",
            "产品白皮书",
            "白皮书",
            "真实产品页面",
            "产品页面",
            "厂商文档",
            "厂商资料",
            "厂商公开资料",
            "行业标准",
            "标准规范",
            "商业沉浸式",
            "单一最接近文献",
            "最接近现有技术确认",
            "继续检索英文专利源",
            "继续检索中文专利源",
            "形成可审计的否定式检索结论",
        )
        if (has_evidence or has_negative_retrieval_audit) and any(
            marker in text for marker in unavailable_source_markers
        ):
            return True

        implementation_detail_markers = (
            "具体数值",
            "可公开范围",
            "尚未量化",
            "参数仍需",
            "真实商业产品",
            "真实产品",
            "真实项目",
            "真实参数",
            "工程参数",
            "研发内部",
            "范围化",
            "可选化",
            "可配置",
            "非限定",
            "实施例示例化",
            "真实产品采用",
            "公开产品采用",
            "公开功能",
            "公开时间",
            "身高区间",
            "身高档位",
            "角度档位",
            "角度阈值",
            "角度区间",
            "场景模式",
            "显示模板参数",
            "执行机构",
            "执行机构型号",
            "传感器型号",
            "显示单元尺寸",
            "屏幕尺寸",
            "角度范围",
            "反馈精度",
            "具体算法",
            "唯一算法",
            "算法选型",
            "画面重构算法",
            "固定实现",
            "拟采用参数",
            "内部产品参数",
            "硬件来源",
        )
        if any(marker in text for marker in implementation_detail_markers):
            return True
        return False

    def _has_auditable_negative_retrieval(self, report: Dict[str, Any]) -> bool:
        """True when retrieval made real attempts and recorded why direct evidence is absent.

        This does not treat missing patent evidence as success. It only lets the
        writer proceed with explicit carried risks after the retrieval Agent has
        documented sources, queries, failures/no-hits, and non-patent or web
        evidence. The writer/reviewer must still cite the limitation honestly.
        """
        if not isinstance(report, dict):
            return False
        if not self._has_real_retrieval_evidence(report):
            return False

        sources = self._extract_retrieval_sources(report)
        evidence_sources = self._as_nonempty_list(report.get("evidence_sources"))
        web_evidence = self._as_nonempty_list(report.get("web_evidence"))
        non_patent = self._as_nonempty_list(report.get("non_patent_prior_art"))
        tool_results = self._as_nonempty_list(report.get("tool_results"))
        if len(sources) + len(evidence_sources) + len(web_evidence) + len(non_patent) < 3:
            return False

        audit_text = "\n".join(
            self._iter_phase_text_values(
                {
                    "retrieval_strategy": report.get("retrieval_strategy"),
                    "retrieval_keywords": report.get("retrieval_keywords"),
                    "retrieval_databases": report.get("retrieval_databases"),
                    "unavailable_sources": report.get("unavailable_sources"),
                    "empty_sources": report.get("empty_sources"),
                    "skipped_sources": report.get("skipped_sources"),
                    "evidence_gaps": report.get("evidence_gaps"),
                    "evidence_sources": report.get("evidence_sources"),
                }
            )
        )
        attempted_patent_source = any(
            marker in audit_text
            for marker in (
                "Google Patents",
                "google_patents",
                "USPTO",
                "CNIPA",
                "中国专利",
                "专利源",
                "专利库",
                "patent_search",
            )
        )
        recorded_no_hit_or_failure = any(
            marker in audit_text
            for marker in (
                "HTTP 503",
                "解析失败",
                "不可用",
                "无法访问",
                "无结果",
                "未取得",
                "未获得",
                "未命中",
                "未见直接",
                "否定式",
                "筛选记录",
            )
        )
        enough_attempts = len(tool_results) >= 3 or len(evidence_sources) >= 3
        return attempted_patent_source and recorded_no_hit_or_failure and enough_attempts

    def _filter_hard_prewriting_gaps(
        self,
        gaps: List[Any],
        retrieval_report: Optional[Dict[str, Any]] = None,
    ) -> List[str]:
        return [
            "\n".join(self._iter_phase_text_values(item))
            if isinstance(item, (dict, list))
            else str(item)
            for item in gaps
            if not self._is_nonblocking_prewriting_gap(item, retrieval_report)
        ]

    def _successful_phase_round_count(
        self,
        context: WorkflowContext,
        phase: WorkflowPhase,
    ) -> int:
        expected_phase = getattr(phase, "value", phase)
        return sum(
            1
            for result in context.phase_history
            if getattr(result.phase, "value", result.phase) == expected_phase and result.success
        )

    def _source_limitation_gap_text(self, item: Any) -> str:
        if isinstance(item, (dict, list)):
            return "\n".join(self._iter_phase_text_values(item))
        return str(item or "")

    def _is_source_limitation_or_prior_art_gap(self, item: Any) -> bool:
        text = self._source_limitation_gap_text(item)
        if not text.strip():
            return True
        source_limitation_markers = (
            "网页正文读取",
            "远程调试",
            "调试端口",
            "浏览器未连接",
            "浏览器连接",
            "web_access",
            "网页读取失败",
            "网页访问失败",
            "无法访问",
            "不可用",
            "未配置",
            "未启用",
            "HTTP 503",
            "解析失败",
            "无结果",
            "未取得",
            "未获得",
            "未命中",
            "未见直接",
            "直接证据",
            "可核验专利",
            "专利对比文件",
            "最接近对比文件",
            "最接近专利",
            "Google Patents",
            "USPTO",
            "CNIPA",
            "中国专利库",
            "专利库",
            "专利源",
            "公开网页证据",
            "证据补强",
            "真伪核验",
            "交叉核验",
        )
        return any(marker in text for marker in source_limitation_markers)

    def _retrieval_limitations_are_carriable(
        self,
        context: WorkflowContext,
        retrieval_report: Dict[str, Any],
    ) -> bool:
        """Workflow policy: do not let unavailable sources create an endless loop.

        Professional Agents still own the technical conclusion. This only says
        that after multiple real retrieval rounds plus requirement review, source
        limitations/no-hit records are carried into drafting and quality review
        instead of blocking forever.
        """
        if not isinstance(retrieval_report, dict):
            return False
        if self._successful_phase_round_count(context, WorkflowPhase.RETRIEVAL) < 2:
            return False
        if not self._retrieval_has_requirement_review(context):
            return False
        if not (
            self._has_real_retrieval_evidence(retrieval_report)
            or self._has_auditable_negative_retrieval(retrieval_report)
        ):
            return False

        limitation_items: List[Any] = []
        strategy = retrieval_report.get("retrieval_strategy")
        if isinstance(strategy, dict):
            limitation_items.extend(self._as_nonempty_list(strategy.get("unavailable_sources")))
            limitation_items.extend(self._as_nonempty_list(strategy.get("empty_sources")))
            limitation_items.extend(self._as_nonempty_list(strategy.get("skipped_sources")))
        for field_name in (
            "evidence_gaps",
            "unavailable_sources",
            "empty_sources",
            "skipped_sources",
            "source_limitations",
        ):
            limitation_items.extend(self._as_nonempty_list(retrieval_report.get(field_name)))

        return any(self._is_source_limitation_or_prior_art_gap(item) for item in limitation_items)

    def _workflow_confirms_public_status(self, context: WorkflowContext) -> bool:
        """Return whether startup discussion already captured the invention public status."""
        confirmed = context.metadata.get("confirmed_preflight")
        if isinstance(confirmed, dict) and str(confirmed.get("public_status") or "").strip():
            return True
        shared = context.metadata.get("shared_agent_context")
        if isinstance(shared, dict):
            preflight = shared.get("confirmed_preflight")
            if isinstance(preflight, dict) and str(preflight.get("public_status") or "").strip():
                return True

        text_parts = [context.original_description]
        text_parts.extend(str(item.get("content") or "") for item in context.message_history)
        combined = "\n".join(part for part in text_parts if part).strip()
        public_status_markers = (
            "尚未公开",
            "未公开",
            "未对外公开",
            "已公开",
            "公开状态",
            "是否公开",
            "申请日前",
        )
        return any(marker in combined for marker in public_status_markers)

    def _gap_closed_by_confirmed_context(self, gap_text: Any, context: WorkflowContext) -> bool:
        text = "\n".join(self._iter_phase_text_values(gap_text)) if isinstance(gap_text, (dict, list)) else str(gap_text or "")
        if not text.strip():
            return True
        confirmed_text = self._confirmed_context_text(context)
        public_status_gap_markers = (
            "产品公开时间",
            "首次公开",
            "对外展示",
            "销售情况",
            "公开状态",
            "申请日前是否存在公开",
        )
        if any(marker in text for marker in public_status_gap_markers):
            return self._workflow_confirms_public_status(context)
        if any(marker in text for marker in ("角度阈值", "角度区间", "显示模板参数")):
            return any(
                marker in confirmed_text
                for marker in ("姿态-显示映射表", "映射表", "不写死", "显示模板参数")
            )
        if any(
            marker in text
            for marker in (
                "补充画面",
                "过渡画面",
                "裁切画面",
                "重构画面",
                "具体算法",
                "唯一算法",
            )
        ):
            return any(
                marker in confirmed_text
                for marker in (
                    "透视变换",
                    "纹理采样",
                    "时序插值",
                    "内容补全",
                    "遮挡掩膜",
                    "边缘羽化",
                    "透明度渐变",
                    "过渡帧",
                    "不限定唯一算法",
                    "可选算法族",
                )
            )
        if any(marker in text for marker in ("姿态检测", "硬件来源", "屏幕姿态检测")):
            return any(
                marker in confirmed_text
                for marker in (
                    "角度传感器",
                    "执行机构反馈",
                    "屏幕控制器状态",
                    "视觉/深度定位",
                    "深度定位",
                )
            )
        return False

    def _confirmed_context_text(self, context: WorkflowContext) -> str:
        """Return all user-confirmed/shared facts visible to workflow gates."""
        parts: List[str] = []
        parts.append(str(context.original_description or ""))
        parts.append(context.get_shared_agent_context_text(limit=20000))
        for msg in context.message_history:
            if msg.get("role") in {"user", "assistant"}:
                parts.append(str(msg.get("content") or ""))
        supplies = context.metadata.get("user_supplemental_info")
        if isinstance(supplies, list):
            parts.extend(str(item) for item in supplies)
        remediation = context.metadata.get("quality_remediation")
        if isinstance(remediation, dict):
            parts.append(str(remediation.get("user_supplied_info") or ""))
        return "\n".join(part for part in parts if part.strip())

    def _requirement_review_allows_drafting(self, retrieval_review: Dict[str, Any]) -> bool:
        """Agent-owned signal that the file can move to drafting with risks carried forward."""
        if not isinstance(retrieval_review, dict):
            return False

        if retrieval_review.get("ready_for_writing") is False:
            return False

        def is_explicitly_nonblocking_gap(item: Any) -> bool:
            if isinstance(item, dict):
                if item.get("blocking_for_writing") is False:
                    return True
                gap_text = "\n".join(
                    str(item.get(key) or "")
                    for key in (
                        "impact",
                        "impact_on_writing",
                        "reason",
                        "recommendation",
                        "gap",
                    )
                )
            else:
                gap_text = str(item or "")
            nonblocking_patterns = (
                "不应阻止撰写",
                "不阻止撰写",
                "不影响当前权利要求骨架",
                "不影响当前权利要求",
                "不影响当前撰写",
                "不改变发明主题",
                "作为检索风险带入撰写",
                "作为撰写和质量审查风险",
                "带入撰写和质量审查",
            )
            return any(pattern in gap_text for pattern in nonblocking_patterns)

        remaining = self._as_nonempty_list(retrieval_review.get("remaining_requirement_gaps"))
        hard_remaining = [
            item
            for item in remaining
            if not is_explicitly_nonblocking_gap(item)
        ]
        if retrieval_review.get("ready_for_writing") is True and (
            retrieval_review.get("all_requirement_gaps_closed") is True or not hard_remaining
        ):
            return True

        text = "\n".join(self._iter_phase_text_values(retrieval_review))
        allow_markers = (
            "具备预撰写基础",
            "可进入预撰写",
            "可启动预撰写",
            "启动预撰写",
            "可启动预撰写草案",
            "可进入预撰写草案",
            "可以进入预撰写",
            "可以启动预撰写",
            "可以进入预撰写或内部草案",
            "可以进入预撰写或内部方案草案",
            "可进入撰写",
            "可以进入撰写",
            "可进入草案",
            "可启动草案",
            "可以进入草案",
            "技术方案层面已具备预撰写基础",
            "已具备预撰写基础",
            "足以支撑预撰写",
            "足以支撑撰写",
            "已足以支撑撰写",
            "足以提示撰写",
        )
        return any(marker in text for marker in allow_markers)

    def _has_real_retrieval_evidence(self, report: Dict[str, Any]) -> bool:
        candidate_fields = (
            "prior_art_references",
            "similar_patents",
            "search_results",
            "patent_results",
            "web_evidence",
            "non_patent_prior_art",
            "evidence_sources",
        )
        for field_name in candidate_fields:
            items = report.get(field_name)
            if isinstance(items, list):
                for item in items:
                    if isinstance(item, dict):
                        reference_id = str(
                            item.get("reference_id")
                            or item.get("patent_id")
                            or item.get("publication_number")
                            or item.get("url")
                            or item.get("title")
                            or ""
                        ).strip()
                        if reference_id:
                            return True
                    elif str(item).strip():
                        return True
            elif isinstance(items, dict) and any(str(v).strip() for v in items.values()):
                return True
        tool_results = report.get("tool_results")
        if isinstance(tool_results, list):
            for result in tool_results:
                if not isinstance(result, dict) or result.get("success") is False:
                    continue
                result_text = "\n".join(self._iter_phase_text_values(result.get("result")))
                if re.search(r"\b(CN|US|EP|WO|JP)\s?\d{4,}", result_text, re.IGNORECASE):
                    return True
                if re.search(r"https?://", result_text):
                    return True
        return False

    def _unwrap_phase_payload(self, value: Any) -> Any:
        """Extract the Agent's structured payload from the Hermes response envelope."""
        if not isinstance(value, dict):
            return value

        metadata = {
            key: value[key]
            for key in (
                "_agent_failed",
                "_agent_error",
                "_incomplete_output",
                "tool_results",
                "duration_seconds",
            )
            if key in value
        }

        structured = value.get("structured_result")
        if isinstance(structured, dict) and structured:
            merged = dict(structured)
            for key, meta_value in metadata.items():
                merged.setdefault(key, meta_value)
            return merged

        for key in ("final_response", "output", "content", "result"):
            text = value.get(key)
            if not isinstance(text, str) or not text.strip():
                continue
            parsed = self._try_parse_json(text)
            if isinstance(parsed, dict) and parsed and "raw_output" not in parsed:
                merged = dict(parsed)
                for meta_key, meta_value in metadata.items():
                    merged.setdefault(meta_key, meta_value)
                return merged

        return value

    def _extract_retrieval_sources(self, report: Dict[str, Any]) -> List[str]:
        """Return only sources backed by actual returned evidence."""
        sources: set[str] = set()

        actual_sources = report.get("actual_sources_used")
        if isinstance(actual_sources, list):
            sources.update(str(item).strip() for item in actual_sources if str(item).strip())

        source_counts = report.get("source_result_counts")
        if isinstance(source_counts, dict):
            for source, count in source_counts.items():
                try:
                    numeric_count = int(count)
                except (TypeError, ValueError):
                    numeric_count = 0
                if numeric_count > 0 and str(source).strip():
                    sources.add(str(source).strip())

        for field_name in ("similar_patents", "prior_art_references", "search_results", "patent_results"):
            items = report.get(field_name)
            if not isinstance(items, list):
                continue
            for item in items:
                if not isinstance(item, dict):
                    continue
                source = (
                    item.get("source")
                    or item.get("database")
                    or item.get("data_source")
                    or item.get("provider")
                )
                if source and str(source).strip():
                    sources.add(str(source).strip())

        for field_name in ("web_evidence", "non_patent_prior_art", "evidence_sources"):
            items = report.get(field_name)
            if not isinstance(items, list):
                continue
            for item in items:
                if isinstance(item, dict):
                    url = str(item.get("url") or item.get("source_url") or "").strip()
                    source = str(item.get("source") or item.get("site") or "").strip()
                else:
                    url = str(item).strip()
                    source = ""
                if source:
                    sources.add(source)
                elif "patents.google.com" in url:
                    sources.add("google_patents")
                elif "uspto.gov" in url:
                    sources.add("uspto")

        return sorted(sources)

    def _uses_public_web_evidence(self, report: Dict[str, Any]) -> bool:
        for field_name in ("web_evidence", "non_patent_prior_art", "evidence_sources"):
            if self._as_nonempty_list(report.get(field_name)):
                return True
        return False

    def _has_professional_or_official_verification(self, report: Dict[str, Any]) -> bool:
        """Check public/web evidence has a professional, official, or patent-office verifier."""
        professional_domains = (
            "patents.google.com",
            "uspto.gov",
            "patentcenter.uspto.gov",
            "ieee.org",
            "acm.org",
            "springer.com",
            "sciencedirect.com",
            "elsevier.com",
            "nature.com",
            "arxiv.org",
            "iso.org",
            "iec.ch",
        )
        verification_markers = (
            "官方",
            "专利局",
            "专业",
            "标准组织",
            "论文",
            "出版",
            "patent office",
            "official",
            "standard",
            "journal",
            "conference",
            "verified",
            "cross-check",
        )
        for field_name in ("similar_patents", "prior_art_references", "search_results", "patent_results"):
            if self._as_nonempty_list(report.get(field_name)):
                return True
        for field_name in ("web_evidence", "non_patent_prior_art", "evidence_sources"):
            for item in self._as_nonempty_list(report.get(field_name)):
                if isinstance(item, dict):
                    text = json.dumps(item, ensure_ascii=False).lower()
                    url = str(item.get("url") or item.get("source_url") or "").strip()
                else:
                    text = str(item).lower()
                    url = str(item).strip()
                if any(marker.lower() in text for marker in verification_markers):
                    return True
                host = urlparse(url).netloc.lower()
                if host.startswith("www."):
                    host = host[4:]
                if any(host == domain or host.endswith("." + domain) for domain in professional_domains):
                    return True
        return False

    def _latest_user_supplemental_text(self, context: WorkflowContext) -> str:
        parts: List[str] = []
        for msg in context.message_history:
            if msg.get("role") == "user":
                parts.append(str(msg.get("content") or ""))
        supplies = context.metadata.get("user_supplemental_info")
        if isinstance(supplies, list):
            parts.extend(str(item) for item in supplies)
        remediation = context.metadata.get("quality_remediation")
        if isinstance(remediation, dict):
            parts.append(str(remediation.get("user_supplied_info") or ""))
        return "\n".join(part for part in parts if part.strip())

    def _requirement_gap_belongs_to_retrieval(self, gap_text: str) -> bool:
        """Requirement gaps that explicitly ask retrieval to verify evidence belong to retrieval."""
        text = str(gap_text or "")
        retrieval_markers = (
            "检索分析阶段",
            "检索阶段",
            "补充检索",
            "继续检索",
            "中国专利",
            "专利库",
            "Google Patents",
            "USPTO",
            "可核验证据",
            "专业/官方",
            "官方或专业",
            "交叉核验",
            "真伪",
            "证据",
            "补证",
            "核验",
            "现有技术",
            "对比文件",
            "最接近",
            "产品页面",
            "白皮书",
            "厂商",
            "标准",
            "专利号",
        )
        return any(marker in text for marker in retrieval_markers)

    def _review_gaps_are_carriable_retrieval_risks(
        self,
        gaps: List[Any],
        retrieval_report: Optional[Dict[str, Any]],
    ) -> bool:
        """Return True when review gaps are retrieval risk notes, not drafting blockers."""
        if not gaps:
            return True
        report = retrieval_report or {}
        if not (
            self._has_real_retrieval_evidence(report)
            or self._has_auditable_negative_retrieval(report)
        ):
            return False
        for item in gaps:
            text = "\n".join(self._iter_phase_text_values(item)) if isinstance(item, (dict, list)) else str(item)
            if not text.strip():
                continue
            if self._is_nonblocking_prewriting_gap(text, report):
                continue
            if self._requirement_gap_belongs_to_retrieval(text):
                continue
            return False
        return True

    def _collect_prewriting_blockers(self, context: WorkflowContext) -> List[Dict[str, str]]:
        """Return blockers that must be resolved before the writer Agent runs.

        The gate only checks workflow readiness. It does not synthesize patent
        substance; unresolved items are routed back to the responsible Hermes Agent.
        """
        blockers: List[Dict[str, str]] = []
        req = self._latest_phase_output(
            context, WorkflowPhase.REQUIREMENT, "requirement_analysis"
        )
        if not isinstance(req, dict) or not req:
            return [{
                "phase": WorkflowState.REQUIREMENT_ANALYSIS.value,
                "severity": "critical",
                "message": "需求分析结果缺失，不能进入专利撰写。",
            }]
        if req.get("_agent_failed") is True:
            blockers.append({
                "phase": WorkflowState.REQUIREMENT_ANALYSIS.value,
                "severity": "critical",
                "message": f"需求分析 Agent 执行失败：{str(req.get('_agent_error') or '')[:220]}",
            })

        required_requirement_fields = [
            ("tech_field", "技术领域"),
            ("core_principle", "核心原理"),
            ("technical_problem", "技术问题"),
            ("beneficial_effects", "有益效果"),
            ("key_innovative_features", "关键创新特征"),
            ("application_scenarios", "应用场景"),
            ("patent_type_recommendation", "专利类型建议"),
            ("claim_skeleton", "权利要求骨架"),
        ]
        for field_name, label in required_requirement_fields:
            value = req.get(field_name)
            if isinstance(value, dict):
                has_value = any(str(v).strip() for v in value.values())
            elif isinstance(value, list):
                has_value = bool(self._as_nonempty_list(value))
            else:
                has_value = bool(str(value or "").strip())
            if not has_value:
                blockers.append({
                    "phase": WorkflowState.REQUIREMENT_ANALYSIS.value,
                    "severity": "high",
                    "message": f"需求分析缺少{label}，撰写前必须由需求分析 Agent 补齐。",
                })

        claim_skeleton = req.get("claim_skeleton")
        if isinstance(claim_skeleton, dict):
            step_count = claim_skeleton.get("step_count")
            steps = claim_skeleton.get("steps")
            actual_step_count = len(steps) if isinstance(steps, list) else step_count
            if actual_step_count not in (3, 4):
                blockers.append({
                    "phase": WorkflowState.REQUIREMENT_ANALYSIS.value,
                    "severity": "high",
                    "message": "需求分析中的独权骨架不是3步或4步，必须先修正保护方案再撰写。",
                })

        ret_preview = self._latest_phase_output(
            context, WorkflowPhase.RETRIEVAL, "retrieval_report"
        )
        if not isinstance(ret_preview, dict) or not ret_preview:
            ret_preview = None
        retrieval_review = req.get("retrieval_feedback_review")
        review_allows_drafting = (
            self._requirement_review_allows_drafting(retrieval_review)
            if isinstance(retrieval_review, dict)
            else False
        )
        has_real_retrieval_evidence = self._has_real_retrieval_evidence(ret_preview or {})
        requirement_allows_drafting = (
            bool(req.get("can_start_drafting") is True or req.get("ready_for_writing") is True)
            or self._requirement_review_allows_drafting(req)
        )

        raw_information_gaps = [
            item
            for item in self._as_nonempty_list(req.get("information_gaps"))
            if not self._gap_closed_by_confirmed_context(item, context)
        ]
        gaps = self._filter_hard_prewriting_gaps(raw_information_gaps, ret_preview)
        filtered_gaps: List[str] = []
        retrieval_gaps: List[str] = []
        for gap in gaps:
            gap_text = str(gap)
            if self._requirement_gap_belongs_to_retrieval(gap_text):
                retrieval_gaps.append(gap_text)
                continue
            filtered_gaps.append(gap_text)
        if review_allows_drafting:
            carried = context.metadata.setdefault("prewriting_carried_risks", {})
            if filtered_gaps:
                carried["requirement_information_gaps"] = filtered_gaps
            if retrieval_gaps:
                carried["retrieval_information_gaps"] = retrieval_gaps
            filtered_gaps = []
            retrieval_gaps = []
        elif requirement_allows_drafting and (
            has_real_retrieval_evidence
            or self._has_auditable_negative_retrieval(ret_preview or {})
        ):
            carried = context.metadata.setdefault("prewriting_carried_risks", {})
            if filtered_gaps:
                carried["requirement_information_gaps"] = filtered_gaps
            if retrieval_gaps:
                carried["retrieval_information_gaps"] = retrieval_gaps
            carried["requirement_review_conclusion"] = str(
                req.get("analysis_confidence_note")
                or req.get("review_conclusion")
                or "需求分析 Agent 已确认足以支撑撰写。"
            )[:2000]
            filtered_gaps = []
            retrieval_gaps = []
        if filtered_gaps:
            blockers.append({
                "phase": WorkflowState.REQUIREMENT_ANALYSIS.value,
                "severity": "high",
                "message": "需求分析仍存在信息缺口，不能直接交给撰写 Agent：" + "；".join(str(item)[:120] for item in filtered_gaps[:5]),
            })
        if retrieval_gaps:
            blockers.append({
                "phase": WorkflowState.RETRIEVAL_ANALYSIS.value,
                "severity": "high",
                "message": "需求分析指出仍需检索阶段补证/核验，不能进入撰写：" + "；".join(str(item)[:120] for item in retrieval_gaps[:5]),
            })
        if self._has_phase_signal(req, "knowledge_insufficient", "genuinely_missing"):
            blockers.append({
                "phase": WorkflowState.REQUIREMENT_ANALYSIS.value,
                "severity": "high",
                "message": "需求分析标记了未解决的信息不足信号，必须先由 CEO 调度补齐或确认。",
            })
        if (
            self._retrieval_has_requirement_review(context)
            and not isinstance(retrieval_review, dict)
            and not (
                requirement_allows_drafting
                and (
                    has_real_retrieval_evidence
                    or self._has_auditable_negative_retrieval(ret_preview or {})
                )
            )
        ):
            blockers.append({
                "phase": WorkflowState.REQUIREMENT_ANALYSIS.value,
                "severity": "high",
                "message": "需求分析已在检索后更新，但未输出 retrieval_feedback_review，必须由需求分析 Agent 明确复核检索是否关闭缺口。",
            })
        if isinstance(retrieval_review, dict):
            ready_for_writing = retrieval_review.get("ready_for_writing")
            all_gaps_closed = retrieval_review.get("all_requirement_gaps_closed")
            raw_remaining = [
                item
                for item in self._as_nonempty_list(
                    retrieval_review.get("remaining_requirement_gaps")
                )
                if not self._gap_closed_by_confirmed_context(item, context)
            ]
            raw_search_feedback = self._as_nonempty_list(
                retrieval_review.get("search_feedback_for_retrieval")
            )
            remaining = self._filter_hard_prewriting_gaps(raw_remaining, ret_preview)
            search_feedback = self._filter_hard_prewriting_gaps(raw_search_feedback, ret_preview)
            carriable_retrieval_risks = (
                self._review_gaps_are_carriable_retrieval_risks(raw_remaining, ret_preview)
                and self._review_gaps_are_carriable_retrieval_risks(
                    raw_search_feedback,
                    ret_preview,
                )
            )
            if review_allows_drafting:
                context.metadata["prewriting_carried_risks"] = {
                    "remaining_requirement_gaps": remaining,
                    "search_feedback_for_retrieval": search_feedback,
                    "review_conclusion": retrieval_review.get("review_conclusion"),
                    "policy": (
                        "需求分析 Agent 已明确 ready_for_writing=true，"
                        "剩余检索项仅作为撰写和质量审查风险继续流转，"
                        "不再触发检索无限循环。"
                    ),
                }
                remaining = []
                search_feedback = []
                ready_for_writing = True
                all_gaps_closed = True
            elif carriable_retrieval_risks:
                carried = context.metadata.setdefault("prewriting_carried_risks", {})
                carried["remaining_requirement_gaps"] = raw_remaining
                carried["search_feedback_for_retrieval"] = raw_search_feedback
                carried["review_conclusion"] = retrieval_review.get("review_conclusion")
                carried["policy"] = (
                    "需求分析复核中的剩余项均为检索证据增强或来源限制；"
                    "已有真实检索证据/失败审计，作为撰写和质量审查风险继续流转。"
                )
                remaining = []
                search_feedback = []
                ready_for_writing = True
                all_gaps_closed = True
            hard_review_blocked = bool(remaining or search_feedback)
            soft_review_flag_only = (
                (review_allows_drafting or not hard_review_blocked)
                and has_real_retrieval_evidence
                and (ready_for_writing is not True or all_gaps_closed is not True)
            )
            if (
                (ready_for_writing is not True or all_gaps_closed is not True or hard_review_blocked)
                and not soft_review_flag_only
            ):
                target_phase = (
                    WorkflowState.RETRIEVAL_ANALYSIS.value
                    if search_feedback or any(self._requirement_gap_belongs_to_retrieval(str(item)) for item in remaining)
                    else WorkflowState.REQUIREMENT_ANALYSIS.value
                )
                detail = "；".join(str(item)[:120] for item in (search_feedback or remaining)[:5])
                if not detail:
                    detail = (
                        "需求分析复核未明确 ready_for_writing=true 且 "
                        "all_requirement_gaps_closed=true，不能进入撰写。"
                    )
                blockers.append({
                    "phase": target_phase,
                    "severity": "high",
                    "message": "需求分析复核认为检索/需求缺口尚未关闭：" + detail,
                })

        ret = self._latest_phase_output(
            context, WorkflowPhase.RETRIEVAL, "retrieval_report"
        )
        if not isinstance(ret, dict) or not ret:
            blockers.append({
                "phase": WorkflowState.RETRIEVAL_ANALYSIS.value,
                "severity": "critical",
                "message": "检索分析结果缺失，不能进入专利撰写。",
            })
            return blockers
        if ret.get("_agent_failed") is True:
            blockers.append({
                "phase": WorkflowState.RETRIEVAL_ANALYSIS.value,
                "severity": "critical",
                "message": f"检索分析 Agent 执行失败：{str(ret.get('_agent_error') or '')[:220]}",
            })

        strategy = ret.get("retrieval_strategy")
        if isinstance(strategy, dict):
            keywords = self._as_nonempty_list(strategy.get("keywords") or ret.get("retrieval_keywords"))
            declared_databases = self._as_nonempty_list(strategy.get("databases_used") or ret.get("retrieval_databases"))
        else:
            keywords = self._as_nonempty_list(ret.get("retrieval_keywords"))
            declared_databases = self._as_nonempty_list(ret.get("retrieval_databases"))
        databases = self._extract_retrieval_sources(ret)
        if not databases and declared_databases and self._has_real_retrieval_evidence(ret):
            databases = declared_databases
        if len(keywords) < 3:
            blockers.append({
                "phase": WorkflowState.RETRIEVAL_ANALYSIS.value,
                "severity": "high",
                "message": "检索策略缺少足够的实际检索关键词，必须补充检索。",
            })
        if not databases:
            blockers.append({
                "phase": WorkflowState.RETRIEVAL_ANALYSIS.value,
                "severity": "high",
                "message": "检索报告未记录实际使用的数据源，必须补充检索证据。",
            })
        if not self._has_real_retrieval_evidence(ret):
            blockers.append({
                "phase": WorkflowState.RETRIEVAL_ANALYSIS.value,
                "severity": "high",
                "message": "检索报告没有可核验的专利或网页证据列表，不能进入撰写。",
            })
        else:
            skipped_sources = self._as_nonempty_list(ret.get("skipped_sources"))
            empty_sources = self._as_nonempty_list(ret.get("empty_sources"))
            unavailable_sources = self._as_nonempty_list(
                ret.get("unavailable_sources")
                or (strategy.get("unavailable_sources") if isinstance(strategy, dict) else [])
            )
            if skipped_sources or empty_sources or unavailable_sources:
                context.metadata.setdefault("prewriting_carried_risks", {})[
                    "retrieval_source_limitations"
                ] = {
                    "skipped_sources": skipped_sources,
                    "empty_sources": empty_sources,
                    "unavailable_sources": unavailable_sources,
                    "policy": (
                        "单个或部分检索源不可用/无结果时跳过并记录；"
                        "只要其他真实来源已有可核验证据，不作为进入撰写的硬阻断。"
                    ),
                }
        retrieval_limitations_are_carriable = self._retrieval_limitations_are_carriable(
            context,
            ret,
        )
        if (
            self._uses_public_web_evidence(ret)
            and not self._has_professional_or_official_verification(ret)
            and not retrieval_limitations_are_carriable
        ):
            blockers.append({
                "phase": WorkflowState.RETRIEVAL_ANALYSIS.value,
                "severity": "high",
                "message": "检索报告使用了公开网页或 Google Patents 候选证据，但没有专业/官方来源交叉核验，必须继续核验真伪。",
            })
        elif (
            self._uses_public_web_evidence(ret)
            and not self._has_professional_or_official_verification(ret)
            and retrieval_limitations_are_carriable
        ):
            context.metadata.setdefault("prewriting_carried_risks", {})[
                "public_web_verification_limitations"
            ] = {
                "policy": (
                    "公开网页/Google 候选证据已尝试交叉核验但受来源不可用或无直接命中限制；"
                    "该限制进入撰写和质量审查，不再触发无限补检。"
                ),
                "items": self._as_nonempty_list(ret.get("evidence_gaps")),
            }
        retrieval_has_newer_requirement_review = self._retrieval_has_requirement_review(context)
        evidence_gaps = self._filter_hard_prewriting_gaps(
            self._as_nonempty_list(ret.get("evidence_gaps")),
            ret,
        )
        latest_requirement_approves_retrieval = (
            retrieval_has_newer_requirement_review
            and (review_allows_drafting or requirement_allows_drafting)
            and self._has_real_retrieval_evidence(ret)
        )
        if evidence_gaps and (
            latest_requirement_approves_retrieval or retrieval_limitations_are_carriable
        ):
            context.metadata.setdefault("prewriting_carried_risks", {})[
                "retrieval_evidence_gaps"
            ] = {
                "items": evidence_gaps,
                "policy": (
                    "检索 Agent 已返回真实证据或可审计的无结果/不可用记录，"
                    "且已完成检索后需求复核；剩余来源限制转交撰写/质检阶段处理，"
                    "不再触发检索无限循环。"
                ),
            }
            evidence_gaps = []
        if evidence_gaps and not retrieval_has_newer_requirement_review:
            blockers.append({
                "phase": WorkflowState.RETRIEVAL_ANALYSIS.value,
                "severity": "high",
                "message": "检索报告仍存在证据缺口：" + "；".join(str(item)[:120] for item in evidence_gaps[:5]),
            })
        has_retrieval_signal = self._has_phase_signal(
            ret,
            "data_source_unavailable",
            "insufficient_evidence",
            "no_results",
        )
        if (
            has_retrieval_signal
            and not retrieval_has_newer_requirement_review
            and (not self._has_real_retrieval_evidence(ret) or evidence_gaps)
            and not retrieval_limitations_are_carriable
        ):
            blockers.append({
                "phase": WorkflowState.RETRIEVAL_ANALYSIS.value,
                "severity": "high",
                "message": "检索报告标记了数据源不可用、无结果或证据不足，必须继续调度检索 Agent 扩展检索。",
            })
        if not retrieval_has_newer_requirement_review:
            blockers.append({
                "phase": WorkflowState.REQUIREMENT_ANALYSIS.value,
                "severity": "high",
                "code": "retrieval_needs_requirement_review",
                "message": "检索分析已更新，但尚未交回需求分析 Agent 复核需求缺口是否全部关闭，不能进入撰写。",
            })

        return blockers

    def _select_prewriting_remediation_phase(self, blockers: List[Dict[str, str]]) -> WorkflowState:
        if any(item.get("code") == "retrieval_needs_requirement_review" for item in blockers):
            return WorkflowState.REQUIREMENT_ANALYSIS
        phases = {item.get("phase") for item in blockers}
        if WorkflowState.RETRIEVAL_ANALYSIS.value in phases:
            return WorkflowState.RETRIEVAL_ANALYSIS
        if WorkflowState.REQUIREMENT_ANALYSIS.value in phases:
            return WorkflowState.REQUIREMENT_ANALYSIS
        return WorkflowState.RETRIEVAL_ANALYSIS

    def _prewriting_blockers_are_retrieval_only(self, blockers: List[Dict[str, str]]) -> bool:
        return bool(blockers) and all(
            item.get("phase") == WorkflowState.RETRIEVAL_ANALYSIS.value for item in blockers
        )

    def _latest_phase_history_index(self, context: WorkflowContext, phase: WorkflowPhase) -> int:
        """Return latest successful phase index in history, or -1 when absent."""
        latest = -1
        expected_phase = getattr(phase, "value", phase)
        for index, result in enumerate(context.phase_history):
            result_phase = getattr(result.phase, "value", result.phase)
            if result_phase == expected_phase and result.success:
                latest = index
        return latest

    def _retrieval_has_requirement_review(self, context: WorkflowContext) -> bool:
        """A retrieval report may feed writing only after requirement Agent reviews it.

        This enforces the domain collaboration loop:
        requirement gaps -> retrieval evidence -> requirement confirmation -> writing.
        The workflow engine does not decide whether the evidence is enough; it only
        requires that the responsible requirement Agent has produced a newer round
        after the latest retrieval round.
        """
        latest_retrieval = self._latest_phase_history_index(context, WorkflowPhase.RETRIEVAL)
        if latest_retrieval < 0:
            return False
        latest_requirement = self._latest_phase_history_index(context, WorkflowPhase.REQUIREMENT)
        return latest_requirement > latest_retrieval

    def _blockers_only_require_retrieval_review(self, blockers: List[Dict[str, str]]) -> bool:
        return bool(blockers) and all(
            item.get("code") == "retrieval_needs_requirement_review"
            for item in blockers
        )

    async def _ensure_prewriting_ready(
        self,
        context: WorkflowContext,
        event_callback: Optional[Callable[[str, str, str, Dict[str, Any]], None]] = None,
        phase_callback: Optional[Callable[[WorkflowState, PhaseResult], None | Awaitable[None]]] = None,
        checkpoint_callback: Optional[Callable[[WorkflowContext, str], None | Awaitable[None]]] = None,
        max_attempts: int = 8,
    ) -> bool:
        attempts = int(context.metadata.get("prewriting_gate_attempts", 0) or 0)
        remediation = context.metadata.get("quality_remediation")
        if (
            isinstance(remediation, dict)
            and remediation.get("classification") == "service_restarted_resume_required"
            and context.current_phase != WorkflowState.AWAITING_USER_DECISION
        ):
            context.metadata.pop("quality_remediation", None)

        while True:
            blockers = self._collect_prewriting_blockers(context)
            if not blockers:
                context.metadata.pop("prewriting_gate_blockers", None)
                remediation = context.metadata.get("quality_remediation")
                if isinstance(remediation, dict) and str(
                    remediation.get("classification") or ""
                ).startswith("prewriting_"):
                    context.metadata.pop("quality_remediation", None)
                context.metadata["prewriting_gate_passed"] = True
                if attempts and event_callback:
                    event_callback(
                        "CEO Agent",
                        "agent.content",
                        "✅ 撰写前置检查已通过：需求分析和检索问题已处理完毕",
                        {
                            "agent_name": "CEO Agent",
                            "phase": "prewriting_gate",
                            "content": "需求分析和检索分析已满足撰写前置条件。",
                        },
                    )
                return True

            context.metadata["prewriting_gate_passed"] = False
            context.metadata["prewriting_gate_blockers"] = blockers
            context.latest_revision_suggestions = [item["message"] for item in blockers]
            issue_text = "\n".join(
                f"{index}. [{item.get('phase')}] {item.get('message')}"
                for index, item in enumerate(blockers[:12], start=1)
            )
            if event_callback:
                event_callback(
                    "CEO Agent",
                    "agent.content",
                    "🛑 撰写前置检查未通过，先补齐需求/检索问题\n" + issue_text,
                    {
                        "agent_name": "CEO Agent",
                        "phase": "prewriting_gate",
                        "content": issue_text,
                        "blockers": blockers,
                        "attempt": attempts,
                    },
                )

            needs_requirement_review = any(
                item.get("code") == "retrieval_needs_requirement_review"
                for item in blockers
            )
            if needs_requirement_review:
                if event_callback:
                    event_callback(
                        "CEO Agent",
                        "agent.dispatch",
                        "🎯 检索结果已更新，先交回 → 需求分析 Agent 复核缺口关闭情况",
                        {
                            "from_agent": "CEO Agent",
                            "to_agent": _PHASE_DISPLAY_NAMES.get(
                                WorkflowState.REQUIREMENT_ANALYSIS,
                                "需求分析 Agent",
                            ),
                            "phase": "prewriting_gate",
                            "task_description": issue_text[:1200],
                            "attempt": attempts,
                        },
                    )
                context.latest_revision_suggestions = [issue_text]
                await self._execute_remediation_phase(
                    context,
                    WorkflowState.REQUIREMENT_ANALYSIS,
                    event_callback=event_callback,
                    phase_callback=phase_callback,
                    checkpoint_callback=checkpoint_callback,
                )
                continue

            needs_user_input = self._prewriting_requires_user_input(blockers)
            retrieval_only = self._prewriting_blockers_are_retrieval_only(blockers)
            retrieval_max_attempts = max(max_attempts, 10)
            effective_max_attempts = retrieval_max_attempts if retrieval_only else max_attempts
            should_discuss_with_user = attempts >= effective_max_attempts
            if should_discuss_with_user and not needs_user_input and not retrieval_only:
                has_requirement_blocker = any(
                    item.get("phase") == WorkflowState.REQUIREMENT_ANALYSIS.value
                    for item in blockers
                )
                if has_requirement_blocker:
                    # Requirement-stage gaps such as implementation variants,
                    # feature mappings, and interaction details should be
                    # refined by the requirement Agent before asking the user.
                    effective_max_attempts = max(effective_max_attempts, 12)
                    should_discuss_with_user = attempts >= effective_max_attempts
            if should_discuss_with_user:
                context.current_phase = WorkflowState.AWAITING_USER_DECISION
                if retrieval_only and not needs_user_input:
                    classification = "retrieval_evidence_discussion_required"
                    hold_message = (
                        "⏸️ 多轮补检后仍无法获得足够可核验证据，需要与用户讨论补充检索线索，"
                        "之后再由 CEO 继续调度检索 Agent。"
                    )
                else:
                    classification = (
                        "prewriting_user_input_required"
                        if needs_user_input
                        else "prewriting_gate_blocked"
                    )
                    hold_message = (
                        "⏸️ 撰写前置闭环已达到自动处理上限，需要与用户讨论后继续。"
                        if not needs_user_input
                        else "⏸️ 撰写前还缺少必须由用户确认的信息，已暂停自动流程。"
                    )
                context.metadata["quality_remediation"] = {
                    "classification": classification,
                    "missing_information": [item["message"] for item in blockers],
                    "attempt_count": attempts,
                    "recommended_next_action": "provide_info",
                    "resume_phase": self._select_prewriting_remediation_phase(blockers).value,
                }
                if event_callback:
                    event_callback(
                        "CEO Agent",
                        "workflow.human_input.requested",
                        hold_message,
                        {
                            "phase": "prewriting_gate",
                            "phase_node": "user_interrupt",
                            "blockers": blockers,
                            "attempt": attempts,
                            "interrupt_type": classification,
                            "resume_phase": context.metadata.get("quality_remediation", {}).get("resume_phase"),
                        },
                    )
                    event_callback(
                        "CEO Agent",
                        "agent.content",
                        hold_message + "\n" + issue_text,
                        {
                            "agent_name": "CEO Agent",
                            "phase": "prewriting_gate",
                            "content": issue_text,
                            "blockers": blockers,
                            "attempt": attempts,
                        },
                    )
                await self._publish_progress_event(
                    context,
                    WorkflowState.AWAITING_USER_DECISION,
                    "waiting",
                )
                if checkpoint_callback:
                    result = checkpoint_callback(context, "prewriting_gate_waiting")
                    if asyncio.iscoroutine(result):
                        await result
                return False

            attempts += 1
            context.metadata["prewriting_gate_attempts"] = attempts
            phase = self._select_prewriting_remediation_phase(blockers)
            dispatch_text = issue_text
            if phase == WorkflowState.RETRIEVAL_ANALYSIS:
                dispatch_text += (
                    "\n\n检索补全要求：先分析为什么无结果或证据不足；"
                    "然后更换检索条件，使用更宽/更窄、中文/英文、同义词和关键技术特征组合继续检索；"
                    "必要时补充公开网页或 Google Patents 证据，并用专业信息网站或官方来源交叉确认真伪；"
                    "禁止编造专利号、申请人、公开日或网页来源。"
                )
            if event_callback:
                event_callback(
                    "CEO Agent",
                    "agent.dispatch",
                    f"🎯 撰写前置检查要求先调度 → {_PHASE_DISPLAY_NAMES.get(phase, phase.value)}（第{attempts}轮）",
                    {
                        "from_agent": "CEO Agent",
                        "to_agent": _PHASE_DISPLAY_NAMES.get(phase, phase.value),
                        "phase": "prewriting_gate",
                        "task_description": dispatch_text[:1200],
                        "attempt": attempts,
                    },
                )
            context.latest_revision_suggestions = [dispatch_text]
            await self._execute_remediation_phase(
                context,
                phase,
                event_callback=event_callback,
                phase_callback=phase_callback,
                checkpoint_callback=checkpoint_callback,
            )
            if (
                phase == WorkflowState.REQUIREMENT_ANALYSIS
                and not self._blockers_only_require_retrieval_review(blockers)
            ):
                if event_callback:
                    event_callback(
                        "CEO Agent",
                        "agent.dispatch",
                        "🎯 需求分析已更新，重新调度 → 检索分析 Agent",
                        {
                            "from_agent": "CEO Agent",
                            "to_agent": _PHASE_DISPLAY_NAMES.get(
                                WorkflowState.RETRIEVAL_ANALYSIS,
                                "检索分析 Agent",
                            ),
                            "phase": "prewriting_gate",
                            "attempt": attempts,
                        },
                    )
                await self._execute_remediation_phase(
                    context,
                    WorkflowState.RETRIEVAL_ANALYSIS,
                    event_callback=event_callback,
                    phase_callback=phase_callback,
                    checkpoint_callback=checkpoint_callback,
                )

    async def _execute_remediation_phase(
        self,
        context: WorkflowContext,
        phase_state: WorkflowState,
        event_callback: Optional[Callable[[str, str, str, Dict[str, Any]], None]] = None,
        phase_callback: Optional[Callable[[WorkflowState, PhaseResult], None | Awaitable[None]]] = None,
        checkpoint_callback: Optional[Callable[[WorkflowContext, str], None | Awaitable[None]]] = None,
    ) -> Dict[str, Any]:
        """复用现有 phase prompt/normalize 逻辑执行单个补救阶段。"""
        if phase_state not in _PHASE_TO_PROFILE or phase_state not in _PHASE_CONTEXT_FIELDS:
            raise ValueError(f"Unsupported remediation phase: {phase_state.value}")

        phase_started_at = time.perf_counter()
        service = _get_agent_factory()
        context.current_phase = phase_state
        await self._publish_progress_event(context, phase_state, "running")
        context_field = _PHASE_CONTEXT_FIELDS[phase_state]
        phase_node = self._node_for_context_field(context_field)
        phase_round = self._phase_round_index(context, phase_node)
        if event_callback:
            event_callback(
                _PHASE_DISPLAY_NAMES.get(phase_state, phase_state.value),
                "workflow.phase_round.started",
                f"{_PHASE_DISPLAY_NAMES.get(phase_state, phase_state.value)} 第{phase_round}轮补救开始",
                {
                    "phase": phase_state.value,
                    "phase_node": phase_node,
                    "round": phase_round,
                    "context_field": context_field,
                    "input_contract": self._phase_contract_summary(context_field),
                    "remediation": True,
                },
            )
        if checkpoint_callback:
            result = checkpoint_callback(context, f"{phase_state.value}_remediation_running")
            if asyncio.iscoroutine(result):
                await result

        task_desc = self._build_phase_continuation_prompt(
            context,
            phase_state,
            self._build_phase_prompt(context, phase_state),
        )
        agent_display_name = _PHASE_DISPLAY_NAMES.get(phase_state, phase_state.value)

        if event_callback:
            event_callback(
                "CEO Agent",
                "agent.dispatch",
                f"🎯 调度 → {agent_display_name}: {task_desc[:100]}",
                {"from_agent": "CEO Agent", "to_agent": agent_display_name, "task_description": task_desc[:300]},
            )

        if phase_state == WorkflowState.PATENT_WRITING:
            context_data = await self._generate_patent_in_sections(
                service,
                _PHASE_TO_PROFILE[phase_state],
                task_desc,
                context,
                event_callback=event_callback,
            )
            if isinstance(context_data, dict):
                context_data = await self._ensure_required_patent_drawings(
                    context,
                    context_data,
                    event_callback=event_callback,
                )
                context_data = self._apply_patent_manual_normalization(
                    context_data,
                    context_title=context.title,
                )
                context_data = await self._refresh_working_draft_docx(
                    context,
                    context_data,
                    checkpoint="补救撰写",
                    event_callback=event_callback,
                )
                context_data = self._clear_stale_writer_failure_if_reviewable(context_data)
                context_data["_writer_postprocessed"] = True
            agent_text = json.dumps(context_data, ensure_ascii=False)[:500] if isinstance(context_data, dict) else str(context_data)[:500]
        else:
            agent_result = await self._run_agent_stream(
                service,
                _PHASE_TO_PROFILE[phase_state],
                task_desc,
                context,
                agent_name=agent_display_name,
                event_callback=event_callback,
            )
            agent_text = agent_result.get("text", "")
            agent_tool_results = agent_result.get("tool_results", [])
            agent_profile_id = {
                WorkflowState.REQUIREMENT_ANALYSIS: "requirement_analyst",
                WorkflowState.RETRIEVAL_ANALYSIS: "retrieval_analyst",
                WorkflowState.QUALITY_REVIEW: "quality_reviewer",
            }.get(phase_state, phase_state.value)
            context_data = self._build_context_data_from_agent_response(
                agent_profile_id,
                agent_text,
                agent_tool_results,
                agent_result.get("structured_result"),
            )

        context_data = self._normalize_phase_output(context_field, context_data)
        contract_issues = self._validate_phase_contract(context_field, context_data)
        if contract_issues:
            context_data = self._build_phase_contract_error(
                context_field,
                context_data,
                contract_issues,
            )
        phase_duration = time.perf_counter() - phase_started_at
        if isinstance(context_data, dict):
            context_data.setdefault("_phase_duration_seconds", phase_duration)
        setattr(context, context_field, context_data)
        previous_shared_facts_version = int(context.metadata.get("shared_facts_version") or 0)
        self._update_shared_context_from_phase(context, context_field, context_data)
        if event_callback and int(context.metadata.get("shared_facts_version") or 0) != previous_shared_facts_version:
            event_callback(
                agent_display_name,
                "workflow.shared_facts.updated",
                f"{agent_display_name} 更新了公共事实",
                {
                    "phase": phase_state.value,
                    "phase_node": phase_node,
                    "round": phase_round,
                    "shared_facts_version": context.metadata.get("shared_facts_version"),
                    "shared_facts_delta": self._summarize_for_checkpoint(
                        context_data.get("shared_facts_delta") if isinstance(context_data, dict) else {},
                        limit=3000,
                    ),
                    "remediation": True,
                },
            )

        saved_path = None
        try:
            saved_path = _persist_phase_result(
                context.task_id,
                context_field,
                context_data if isinstance(context_data, dict) else {"output": str(context_data)},
            )
        except Exception:
            pass

        phase_enum = _PHASE_TO_WORKFLOW_PHASE.get(phase_state, WorkflowPhase.BRAINSTORM)
        agent_failed = isinstance(context_data, dict) and context_data.get("_agent_failed") is True
        if not agent_failed:
            self._invalidate_downstream_outputs(
                context,
                phase_state,
                reason="remediation_phase_completed",
                preserve_fields=self._preserve_downstream_fields_after_phase(
                    phase_state,
                    context_data,
                ),
            )
        phase_result = PhaseResult(
            phase=phase_enum,
            success=not agent_failed,
            duration_seconds=phase_duration,
            output=context_data if isinstance(context_data, dict) else {},
            issues=[str(context_data.get("_agent_error", ""))] if agent_failed and isinstance(context_data, dict) else [],
        )
        context.add_phase_result(phase_result)
        round_record = self._record_phase_round(
            context,
            node=phase_node,
            context_field=context_field,
            status="failed" if agent_failed else "completed",
            output=context_data,
            duration_seconds=phase_duration,
            issues=phase_result.issues,
            artifact_path=saved_path,
        )

        if event_callback:
            event_callback(
                agent_display_name,
                "agent.content",
                "📄 输出",
                {"agent_name": agent_display_name, "content": agent_text if agent_text else "", "phase": phase_state.value},
            )
            event_callback(
                agent_display_name,
                "workflow.phase_round.completed",
                f"{agent_display_name} 第{phase_round}轮补救{'失败' if agent_failed else '完成'}",
                {
                    "phase": phase_state.value,
                    "phase_node": phase_node,
                    "round": phase_round,
                    "round_record": round_record,
                    "remediation": True,
                },
            )

        await self._publish_progress_event(context, phase_state, "failed" if agent_failed else "completed")
        if phase_callback:
            result = phase_callback(phase_state, phase_result)
            if asyncio.iscoroutine(result):
                await result
        if checkpoint_callback:
            result = checkpoint_callback(
                context,
                f"{phase_state.value}_remediation_{'failed' if agent_failed else 'completed'}",
            )
            if asyncio.iscoroutine(result):
                await result
        return context_data if isinstance(context_data, dict) else {}

